### ISSUE TITLE
Bump Static.jl compat

### ISSUE THREAD

**Issue by gaurav-arya** [JuliaMath/MeasureTheory.jl#259]
The current upper bound on `Static.jl` prevents the use of Measure Theory in my environment. In particular, the following combination of packages:
```
Status `/tmp/jl_fZXl7T/Project.toml`
  [79e6a3ab] Adapt v3.6.2
⌅ [4fba245c] ArrayInterface v6.0.17
⌃ [2b5f629d] DiffEqBase v6.95.2
[eadaa1a4] MeasureTheory v0.18.4
[90137ffa] StaticArrays v1.6.2
```
force the outdated `ArrayInterfaceStaticArrays` extension to be loaded, because newer versions of `DiffEqBase` require Static > 0.7. This causes a warning (below) on 1.9, which in fact has been [turned into an error](https://github.com/JuliaLang/julia/discussions/50725) in 1.10 meaning that the environment no longer ~works~ precompiles on 1.10:
![image](https://github.com/JuliaMath/MeasureTheory.jl/assets/43899491/86057f9c-b094-484e-b1f7-9ac2a223cf15)
Bumping the Static.jl compat to 0.8 (https://github.com/JuliaMath/MeasureTheory.jl/pull/245), fixing any breaking changes?, would fix these issues

**Comment by cscherrer** [comment]
Hi @gaurav-arya , yes we need to move this forward. But we can't just bump the Static version, we'll also need to update to depend on the newest MeasureBase.jl (any MB older than 0.14 depends on older Static.jl). MeasureBase has been moving forward quickly, and we need MT to catch up. This is a high priority for this package; we'll try to make progress on this in the next short while.
